### ISSUE TITLE
Error when scraping website 

### ISSUE THREAD

**Issue by RaphSfeir** [Anonyfox/elixir-scrape#35]
I encouter a crash when running `Scrape.website "gamasutra.com"` on my local latest `master` version. This crash only occurs with specific websites (just found gamasutra and 3djuego.com to be crashing), had no issues with others. 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 41584, error_len: Some(1) }', /checkout/src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
  ** (FunctionClauseError) no function clause matching in Floki.HTMLTree.build/1    
    
    The following arguments were given to Floki.HTMLTree.build/1:
    
        # 1
        {:error,
         "called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 41584, error_len: Some(1) }"}
    
    Attempted function clauses (showing 2 out of 2):
    
        def build({tag, attrs, children})
        def build(html_tuples) when is_list(html_tuples)
    
    (floki) lib/floki/html_tree.ex:14: Floki.HTMLTree.build/1
    (floki) lib/floki/finder.ex:48: Floki.Finder.find_selectors/2
    (floki) lib/floki.ex:146: Floki.find/2
    (scrape) lib/scrape/exquery.ex:45: Scrape.Exquery.attr/4
    (scrape) lib/scrape/website.ex:26: Scrape.Website.parse/2

```

Not really sure where the problem is located as I'm not familiar with the whole Rust stack behind it. 
I don't have this issue with the hex `~> 2.0` version. Is there a way to know which commit matches the hex 2.0 release? And / or how to fix the crash would also be awesome. 

Thanks

**Comment by julienmarie** [comment]
This apparently happen because html5ever is not compatible with non utf-8 websites. We need an encoding detection + conversion to utf8 on the fly

**Comment by julienmarie** [comment]
Tried with the latest commit, it's still broken.
Example page that can't be parsed: http://www.lapetitefrance.biz/dinner.htm
Or this one : http://www.littleexplorers.com/languages/french/subjects/food.shtml

**Comment by Anonyfox** [comment]
Works in v3 now: 

```bash
iex(1)> Scrape.domain "https://gamasutra.com"
{:ok,
 %{
   description: "Daily news, interviews, features, and developer blogs about the Art & Business of Making Games.",
   feed_urls: ["http://feeds.feedburner.com/GamasutraFeatureArticles/",
    "http://feeds.feedburner.com/GamasutraNews/",
    "http://feeds.feedburner.com/GamasutraColumns/",
    "http://feeds.feedburner.com/GamasutraJobs/",
    "http://gamasutra.com/static2/rssfeeds.html",
    "http://feeds.feedburner.com/GamasutraJobs",
    "https://gamasutra.com/blogs/rss/",
    "https://gamasutra.com/pressreleases/rss/",
    "https://www.gamasutra.com/view/feature/131493/baldurs_gate_ii_the_anatomy_of_a_.php#comments",
    "https://www.gamasutra.com/view/feature/131493/baldurs_gate_ii_the_anatomy_of_a_.php"],
   icon_url: nil,
   title: "Gamasutra",
   url: "https://gamasutra.com"
 }}
```

Note that "website" is now called "domain".
